name: Enviar seu projeto
description: Inscreva seu projeto já finalizado
title: "Nome do projeto"
labels: []
projects: ["octo-org/1", "octo-org/44"]
body:
  - type: markdown
    attributes:
      value: |
        <br>
        Obrigado por confiar na nossa plataforma, preencha o formulário a seguir, seu projeto será avaliado internamente e então publicado<br>
        
        > **Lembrando que:** Esse formulário destina-se a projetos já em produção, para projetos em desenvolvimento use [esse formulário](link)
        
        <br>
  - type: input
    id: pitch
    attributes:
      label: Descrição rápida do projeto
      placeholder: Em até 25 palavras descreva seu projeto
    validations:
      required: true
  - type: textarea
    id: intro
    attributes:
      label: Introdução
      render: plain
      placeholder: Descreva seus projeto em uma linguagem não técnica, de uma forma simples e objetiva, o ideal é ter menos de 140 caracteres (excluindo pontuação)
    validations:
      required: true
  - type: textarea
    id: descricao
    attributes:
      label: Descricao
      render: plain
      placeholder: Descreva seu projeto de forma mais detalhada, porém ainda forma simples e objetiva esse não é um espaço para documentação, o ideal é ter menos de 400 caracteres (excluindo pontuação)
    validations:
      required: true
  - type: checkboxes
    id: utm
    attributes:
      label: Marketing
      description: Deseja que preenchamos os parâmetros [UTM](https://pt.wikipedia.org/wiki/Par%C3%A2metros_UTM) na sua URL?
      options:
        - label: Sim, adicione os seguinte parametros UTM: 
  - type: markdown
    attributes:
      value: |

        | Parâmetro    | Significado                                                                    | Valor            |
        |--------------|--------------------------------------------------------------------------------|------------------|
        | utm_source   | Identifica qual site enviou o tráfego.	                                        | dev-home-place   |
        | utm_medium   | Identifica que tipo de link foi usado, como CPM ou e-mail.	                    | cpm              |
        | utm_campaign | Identifica uma promoção específica de produto ou campanha estratégica.         | elementary_pitch |
        | utm_content  | Identifica especificamente o que foi clicado para direcionar o usuário ao site | banner           |
        <br>
  - type: input
    id: url
    attributes:
      label: Link para o seu projeto
      description: Não use links para repositórios `git` ou similares, se seu projeto não possui uma página pode usar o [GitHub Pages](https://pages.github.com/) gratuitamente para criar uma
      placeholder: https://meu-projeto.com
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Categoria
      description: Em qual categoria seu projeto se enquadra? 
      options:
        - Audiovisual
        - Áudio
        - Vídeo
        - Desenvolvimento
        - Desenvolvimento jogos
        - Educação
        - Plataforma educacional
        - Jogos
        - Gráficos 2D
        - Gráficos 3D
        - Rede
        - Navegadores
        - Escritório/Produtividade
        - Ciência
        - Utilitário
        - Newsletter
        - Fintech
    validations:
      required: true
  - type: markdown
    attributes:
      value: |

        | Categoria                | Significado                                                                    |
        |--------------------------|--------------------------------------------------------------------------------|
        | Audiovisual              | Lida com conteúdo multimidia	                                        |
        | Áudio                    | Um software que atua com áudio	                    |
        | Vídeo                    | Um software que atua com vídeo        |
        | Desenvolvimento          | Um software usado para o desenvolvimento de software |
        | Desenvolvimento jogos    | Um software usado para o desenvolvimento de jogos |
        | Educação                 | Um software usado para o desenvolvimento de jogos |
        | Plataforma educacional   | Um software usado para o desenvolvimento de jogos |
        | Jogos                    | Um software que atua com imagens 2D|
        | Gráficos 2D              | Um software que atua com imagens 2D|
        | Gráficos 3D              | Um software que atua com imagens 2D|
        | Navegadores              | Um software que atua com imagens 2D|
        | Escritório/Produtividade | Um software que atua com imagens 2D|
        | Ciência                  | Um software que atua com imagens 2D|
        | Utilitário               | Um software que atua com imagens 2D|
        | Newsletter               | Um software que atua com imagens 2D|
        | Fintech                  | Um software que atua com imagens 2D|
        <br>
  - type: dropdown
    id: startup
    attributes:
      label: Empresa
      description: Seu projeto se enquadra no modelo [SaaS](https://pt.wikipedia.org/wiki/Software_como_servi%C3%A7o) ou [Startup](https://pt.wikipedia.org/wiki/Startup)?
      options:
        - Não
        - Sim, um SaaS
        - Sim, ums Startup
    validations:
      required: true
  - type: input
    id: icon
    attributes:
      label: Link para o ícone do projeto
      description: Formato PNG resolução de 256x256
      placeholder: https://meu-projeto.com/icon.png
    validations:
      required: true
  - type: input
    id: screenshot1
    attributes:
      label: Link para a captura de tela principal
      description: Formato PNG, recomendada a resolução de 1280x720
      placeholder: https://meu-projeto.com/screenshot1.png
    validations:
      required: true
  - type: input
    id: screenshot2
    attributes:
      label: Link para a captura de tela secundária
      description: Formato PNG, recomendada a mesma resolução do screenshot1
      placeholder: https://meu-projeto.com/screenshot2.png
  - type: input
    id: screenshot3
    attributes:
      label: Link para a captura de tela extra
      description: Formato PNG, recomendada a mesma resolução do screenshot1
      placeholder: https://meu-projeto.com/screenshot3.png
  - type: checkboxes
    id: especificidades
    attributes:
      label: Recursos
      options:
        - label: API
          required: false
        - label: App Android
          required: false
        - label: App iOS
          required: false
        - label: App HarmonyOS
          required: false
        - label: App Linux
          required: false
        - label: App Mac
          required: false
        - label: App Windows
          required: false
        - label: Extensão para navegador
          required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Condições da plataforma
      description: Para ter seu projeto aprovado, você precisa cumprir certos requisitos, uma versão mais detalhada dos requisitos [se encontra aqui](https://example.com). 
      options:
        - label: Meu projeto está finalizado (saiu da fase MVP/Beta/RC)
          required: true
        - label: Meu projeto permite teste gratuito das suas funcionalidades básicas (pode ser limitado por tempo)
          required: true
        - label: Meu projeto não é uma casa de apostas e/ou market place de produtos e/ou serviços que causam danos a sociedade
          required: true
        - label: Meu projeto não viola nenhuma lei vigente no Brasil
          required: true
        - label: Meu projeto não possui conteúdo pornografico, gore ou afins
          required: true
        - label: Eu possuo todo e qualquer direito sobre o projeto
          required: true
